"""Regenerate CONTRIBUTIONS.md from merged pull requests to repos I don't own."""

import json
import os
import urllib.parse
import urllib.request
from collections import defaultdict
from datetime import datetime, timezone

USER = os.environ.get("GH_USER", "aniketsahu28m")
TOKEN = os.environ.get("GITHUB_TOKEN")
OUT = os.path.join(os.path.dirname(__file__), "..", "CONTRIBUTIONS.md")


def search(query):
    items, page = [], 1
    while True:
        url = "https://api.github.com/search/issues?" + urllib.parse.urlencode(
            {"q": query, "per_page": 100, "page": page, "sort": "created", "order": "desc"}
        )
        req = urllib.request.Request(url, headers={"Accept": "application/vnd.github+json"})
        if TOKEN:
            req.add_header("Authorization", f"Bearer {TOKEN}")
        with urllib.request.urlopen(req) as resp:
            batch = json.load(resp)["items"]
        items += batch
        # The search API caps results at 1000.
        if len(batch) < 100 or page == 10:
            return items
        page += 1


def repo_name(pr):
    return pr["repository_url"].removeprefix("https://api.github.com/repos/")


def strip_timestamp(text):
    return "\n".join(l for l in text.splitlines() if not l.startswith("_Last updated:"))


def main():
    prs = search(f"author:{USER} is:pr is:merged -user:{USER}")

    by_repo = defaultdict(list)
    for pr in prs:
        by_repo[repo_name(pr)].append(pr)
    # Repos with the most merged PRs first.
    repos = sorted(by_repo, key=lambda r: (-len(by_repo[r]), r.lower()))

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        "# Contributions",
        "",
        f"Merged pull requests by [@{USER}](https://github.com/{USER}) to projects I don't own.",
        "",
        f"![Merged PRs](https://img.shields.io/badge/Merged_PRs-{len(prs)}-8957e5?style=for-the-badge&logo=githubactions&logoColor=white)"
        f" ![Projects](https://img.shields.io/badge/Projects-{len(repos)}-0e75b6?style=for-the-badge&logo=github&logoColor=white)",
        "",
        f"_Last updated: {now} (auto-generated by GitHub Actions, don't edit by hand)._",
        "",
    ]

    if not prs:
        lines += ["No merged pull requests to other projects yet. Watch this space!", ""]

    for repo in repos:
        lines += [
            f"## [{repo}](https://github.com/{repo})",
            "",
            "| PR | Title | Merged |",
            "|---|---|---|",
        ]
        for pr in sorted(by_repo[repo], key=lambda p: p["pull_request"]["merged_at"] or "", reverse=True):
            title = pr["title"].replace("|", "\\|")
            merged = (pr["pull_request"]["merged_at"] or "")[:10]
            lines.append(f"| [#{pr['number']}]({pr['html_url']}) | {title} | {merged} |")
        lines.append("")

    lines += ["[← Back to profile](./README.md)", ""]

    content = "\n".join(lines)
    # Only rewrite when something other than the timestamp changed, so the
    # workflow doesn't commit every day.
    if os.path.exists(OUT):
        with open(OUT, encoding="utf-8") as f:
            if strip_timestamp(f.read()) == strip_timestamp(content):
                print("No new contributions")
                return
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"Wrote {len(prs)} PRs across {len(repos)} repos")


if __name__ == "__main__":
    main()
